version: "3"

services:
  nginx:
    build: requirements/nginx/
    env_file: .env # maybe not needed for every service
    container_name: nginx
    ports:
      - "80:80"
    restart: always
  mariadb:
    build: requirements/mariadb/
    env_file: .env
    container_name: mariadb
    restart: always
