# version: '3.8'
# version field is obsolete

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file: .env # maybe not needed for every service
    ports:
      - 443:443
    # volumes:
    #   - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  # mariadb:
  #   build: requirements/mariadb/
  #   env_file: .env
  #   container_name: mariadb
  #   restart: always


networks:
  inception:
    driver: bridge